#

application:
  appName: smarter-k3s-server

image:
  repository: rancher/k3s
  # @default -- chart.appVersion
  tag: ""
  pullPolicy: IfNotPresent

configuration:
  hostIP: 192.168.2.222
  # Use this in case of NATed AWS
  #externalHostIP: 192.168.2.222
  port: 6443
  portHTTPS: 6453
  # set id to paqssword
